# fly.toml app configuration file generated for site-polished-fog-5586 on 2024-11-05T10:48:03+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'site-polished-fog-5586'
primary_region = 'syd'

[build]
  image = 'ghcr.io/ovyerus/site:latest'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
