name: Push
on:
  push:
    branches:
      - master

jobs:
  docker:
    name: Build Docker container and push to registry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build Docker image
        run: nix build .#container
      - run: nix flake check

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker load < result
          docker tag ovyerus-site-container ghcr.io/ovyerus/site:latest
          docker push ghcr.io/ovyerus/site:latest
